//This file is generated by VisualGDB and is used to get accurate IntelliSense
#pragma once
#include <Arduino.h>

#define SYSPROGS_ARDUINO_EXPAND_GENERATED_PROTOTYPES \
	void setup(); \
	void loop(); \
	void onStationModeConnected(system_event_id_t event, system_event_info_t info); \
	void handleSettings(AsyncWebServerRequest * request); \
	void handleFileReadAuth(AsyncWebServerRequest * request); \
	void handleScaleProp(AsyncWebServerRequest * request); \
	void handleBatteryPng(AsyncWebServerRequest * request); \
	void handleScalesPng(AsyncWebServerRequest * request); \
	void handleRSSI(AsyncWebServerRequest * request); \
	void printScanResult(int networksFound); \
	void onWsEvent(AsyncWebSocket * server, AsyncWebSocketClient * client, AwsEventType type, void * arg, uint8_t *data, size_t len); \
	void reconnectWifi(AsyncWebServerRequest * request); \
	void handleSeal(AsyncWebServerRequest * request); \
	boolean isIp(String str); \
	String toStringIp(IPAddress ip); \
	int StringSplit(String sInput, char cDelim, String sParams[], int iMaxParams); \

